--
-- LibSQL SQL Schema dump automatic generated by geni
--
CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);

CREATE TABLE chat (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    messages BLOB NOT NULL
);
