// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat.sql

package db

import (
	"context"
	"database/sql"
)

const findChat = `-- name: FindChat :one
SELECT
    title,
    messages
FROM
    chat
WHERE
    id = ?
`

type FindChatRow struct {
	Title    sql.NullString
	Messages []byte
}

func (q *Queries) FindChat(ctx context.Context, id string) (FindChatRow, error) {
	row := q.db.QueryRowContext(ctx, findChat, id)
	var i FindChatRow
	err := row.Scan(&i.Title, &i.Messages)
	return i, err
}

const saveChat = `-- name: SaveChat :exec
INSERT INTO
    chat (id, title, messages)
VALUES
    (?, ?, ?)
`

type SaveChatParams struct {
	ID       string
	Title    sql.NullString
	Messages []byte
}

func (q *Queries) SaveChat(ctx context.Context, arg SaveChatParams) error {
	_, err := q.db.ExecContext(ctx, saveChat, arg.ID, arg.Title, arg.Messages)
	return err
}

const updateChat = `-- name: UpdateChat :exec
UPDATE
    chat
SET
    messages = ?
WHERE
    id = ?
`

type UpdateChatParams struct {
	Messages []byte
	ID       string
}

func (q *Queries) UpdateChat(ctx context.Context, arg UpdateChatParams) error {
	_, err := q.db.ExecContext(ctx, updateChat, arg.Messages, arg.ID)
	return err
}
