// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: graph.sql

package db

import (
	"context"
)

const getGraph = `-- name: GetGraph :many
SELECT
    c.id,
    c.title,
    c.updated_at,
    t.name
FROM
    chat_tag t
    INNER JOIN chat c ON t.chat_id = c.id
`

type GetGraphRow struct {
	ID        string
	Title     string
	UpdatedAt int64
	Name      string
}

func (q *Queries) GetGraph(ctx context.Context) ([]GetGraphRow, error) {
	rows, err := q.db.QueryContext(ctx, getGraph)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGraphRow
	for rows.Next() {
		var i GetGraphRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
