// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Chat struct {
	ID        string
	Title     string
	Messages  []byte
	CreatedAt int64
	UpdatedAt int64
}

type ChatTag struct {
	ChatID string
	Name   string
}

type Mention struct {
	SourceID string
	TargetID string
}

type SchemaMigration struct {
	ID string
}
