// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Chat struct {
	ID       string
	Title    string
	Messages []byte
}

type SchemaMigration struct {
	ID string
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}
